### ISSUE TITLE
Update to new Version

### ISSUE THREAD

**Issue by dragonito** [blai30/Lotus-Material-Theme#1]
Hi there,

i´m using PhpStorm with your Theme. Its incompatible to the newes Version :(  (2019.3)

Thanks a lot

Robin

**Comment by blai30** [comment]
Have you installed version 1.1.3 of the plugin?

**Comment by dragonito** [comment]
Ohhhh :D i removed it, my plugin manager said its incompatible when i had a second look for it... but... reinstalled it, perfect! Perhaps some spooky caches in plugin manager shows incompatibily. Thanks a lot for support!
