### ISSUE TITLE
Light theme font color 

### ISSUE THREAD

**Issue by victor-timofei** [blai30/Lotus-Material-Theme#2]
In Goland with the Light theme when using `fmt.Println()`, `fmt` font color is white and indistinguishable from the white background. 
[Screenshot @ imgur](https://imgur.com/SP9UxBr)

**Comment by blai30** [comment]
Hi, the issue should be fixed in version 1.2.0.
https://github.com/blai30/Lotus-Theme/commit/40e841be6dd601fea85720d80032b675c830fc80
