### ISSUE TITLE
A lot of items in Lotus Light use fcfcfa as a foreground color.

### ISSUE THREAD

**Issue by Minalien** [blai30/Lotus-Material-Theme#3]
This color is basically invisible against the background (see included image, a screenshot from CLion). Similar/related to #2, but this is still the case with v1.2.0.

```c
typedef struct {
    uint8_t *code;
} Chunk;
```

![image](https://user-images.githubusercontent.com/303723/79503430-ff8eac00-7fe5-11ea-9967-d16c7c873cf0.png)

**Comment by blai30** [comment]
Just pushed https://github.com/blai30/Lotus-Theme/commit/3fd65befb20ecf3ccbe85b402c68df33319f64de and uploaded to Plugin Marketplace for verification.

Let me know if there are still issues!

**Comment by Minalien** [comment]
Hmm.. It looks like some of these are still having trouble even with 1.2.2?

![image](https://user-images.githubusercontent.com/303723/79610404-56ab8400-80ad-11ea-9305-8a1d967091c3.png)
![image](https://user-images.githubusercontent.com/303723/79610515-86f32280-80ad-11ea-8226-624173ad2d42.png)

Just to be certain, I uninstalled and reinstalled the plugin completely, but I'm still running into these identifiers being invisible. Inspecting the pixels in Pixelmator, it looks like they're still fcfcfa? 🤔

**Comment by blai30** [comment]
Hmm that's weird. They show up normally for me (tested both C and C++).

![image](https://user-images.githubusercontent.com/29187599/79612890-58c41180-80b2-11ea-9835-79d910c25e2a.png)

Have you tried File -> Settings -> Editor -> Color Scheme -> Restore Defaults?

**Comment by Minalien** [comment]
That seems to have cleared things up! Thanks for that, and sorry for the noise!

Probably got out of sync there because I made it use Comic Code. I'll go ahead and close this up - thanks again! (And thanks for the theme in general! 💜)

**Comment by blai30** [comment]
Glad I could help :)
